/*
 * Elevation service
 *
 * The elevation service is a location service which returns TopoBathy elevation values that combine topography (land elevation) and bathymetry (water depths).
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Elevations : A structure containing a collection of points which contain elevation values (defined as Z). When returned from a request to the `/elevation/at-many-points` endpoint, the order of the points will match the order of the points in the request. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Elevations {
    #[serde(rename = "points")]
    pub points: Vec<models::Point>,
}

impl Elevations {
    /// A structure containing a collection of points which contain elevation values (defined as Z). When returned from a request to the `/elevation/at-many-points` endpoint, the order of the points will match the order of the points in the request. 
    pub fn new(points: Vec<models::Point>) -> Elevations {
        Elevations {
            points,
        }
    }
}

