/*
 * Elevation service
 *
 * The elevation service is a location service which returns TopoBathy elevation values that combine topography (land elevation) and bathymetry (water depths).
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElevationAtPointGet200Response {
    #[serde(rename = "elevationInfo")]
    pub elevation_info: Box<models::ElevationInfo>,
    #[serde(rename = "result")]
    pub result: Box<models::Elevation>,
}

impl ElevationAtPointGet200Response {
    pub fn new(elevation_info: models::ElevationInfo, result: models::Elevation) -> ElevationAtPointGet200Response {
        ElevationAtPointGet200Response {
            elevation_info: Box::new(elevation_info),
            result: Box::new(result),
        }
    }
}

