/*
 * Elevation service
 *
 * The elevation service is a location service which returns TopoBathy elevation values that combine topography (land elevation) and bathymetry (water depths).
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Elevation : A structure containing a point including an elevation value (defined as Z).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Elevation {
    #[serde(rename = "point")]
    pub point: Box<models::Point>,
}

impl Elevation {
    /// A structure containing a point including an elevation value (defined as Z).
    pub fn new(point: models::Point) -> Elevation {
        Elevation {
            point: Box::new(point),
        }
    }
}

