/*
 * Elevation service
 *
 * The elevation service is a location service which returns TopoBathy elevation values that combine topography (land elevation) and bathymetry (water depths).
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ElevationInfo : A structure containing human readable metadata about the specified point.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElevationInfo {
    /// The reference position (datum) from which to measure elevation. The valid values are: - meanSeaLevel: The elevation above or below the WGS84 geoid reference surface, which is approximately the mean sea level.                 It takes into account the local variations in gravity and provides a consistent vertical reference. - ellipsoid: Ellipsoidal height is measured with respect to an ellipsoid, which is a mathematical model that approximates the shape of the Earth.               It does not consider local variations in gravity and is commonly used in GPS positioning. 
    #[serde(rename = "relativeTo")]
    pub relative_to: RelativeTo,
}

impl ElevationInfo {
    /// A structure containing human readable metadata about the specified point.
    pub fn new(relative_to: RelativeTo) -> ElevationInfo {
        ElevationInfo {
            relative_to,
        }
    }
}
/// The reference position (datum) from which to measure elevation. The valid values are: - meanSeaLevel: The elevation above or below the WGS84 geoid reference surface, which is approximately the mean sea level.                 It takes into account the local variations in gravity and provides a consistent vertical reference. - ellipsoid: Ellipsoidal height is measured with respect to an ellipsoid, which is a mathematical model that approximates the shape of the Earth.               It does not consider local variations in gravity and is commonly used in GPS positioning. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RelativeTo {
    #[serde(rename = "meanSeaLevel")]
    MeanSeaLevel,
    #[serde(rename = "ellipsoid")]
    Ellipsoid,
}

impl Default for RelativeTo {
    fn default() -> RelativeTo {
        Self::MeanSeaLevel
    }
}

