/*
 * Elevation service
 *
 * The elevation service is a location service which returns TopoBathy elevation values that combine topography (land elevation) and bathymetry (water depths).
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Format : Optional, case-sensitive parameter to specify the format in which responses are given. Can either be `json` or `pjson`.
/// Optional, case-sensitive parameter to specify the format in which responses are given. Can either be `json` or `pjson`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "json")]
    Json,
    #[serde(rename = "pjson")]
    Pjson,

}

impl std::fmt::Display for Format {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Json => write!(f, "json"),
            Self::Pjson => write!(f, "pjson"),
        }
    }
}

impl Default for Format {
    fn default() -> Format {
        Self::Json
    }
}

