/*
 * Elevation service
 *
 * The elevation service is a location service which returns TopoBathy elevation values that combine topography (land elevation) and bathymetry (water depths).
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Point : A geometry point referring to a location on a map.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Point {
    #[serde(rename = "spatialReference")]
    pub spatial_reference: Box<models::PointSpatialReference>,
    /// The X coordinate which is measured along the east/west axis.
    #[serde(rename = "x")]
    pub x: f64,
    /// The Y coordinate which is measured along the north/south axis.
    #[serde(rename = "y")]
    pub y: f64,
    /// The Z coordinate represents the vertical position of a point above or below a reference level, such as sea level (in meters, rounded to the nearest meter).
    #[serde(rename = "z")]
    pub z: f64,
}

impl Point {
    /// A geometry point referring to a location on a map.
    pub fn new(spatial_reference: models::PointSpatialReference, x: f64, y: f64, z: f64) -> Point {
        Point {
            spatial_reference: Box::new(spatial_reference),
            x,
            y,
            z,
        }
    }
}

