/*
 * Elevation service
 *
 * The elevation service is a location service which returns TopoBathy elevation values that combine topography (land elevation) and bathymetry (water depths).
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PointSpatialReference : The spatial reference system the point is relative to.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PointSpatialReference {
    /// The Well-Known ID (WKID) value of the spatial reference.
    #[serde(rename = "wkid")]
    pub wkid: f64,
}

impl PointSpatialReference {
    /// The spatial reference system the point is relative to.
    pub fn new(wkid: f64) -> PointSpatialReference {
        PointSpatialReference {
            wkid,
        }
    }
}

