/*
 * Basemap styles service
 *
 * The basemap styles service provides global basemap layers in a variety of styles to use in mapping applications. Basemap layers give geographic context to a map or scene by serving static tiles containing geographic reference data. This data includes, but is not limited to, topographic features, road networks, footpaths, building footprints, water features, administrative boundaries, and localized language place labels. The JSON structure of a basemap style can be returned as the [Mapbox Style Specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/) or the Esri [Web Map Specification](https://developers.arcgis.com/web-map-specification/).
 *
 * The version of the OpenAPI document: 2.4.7
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServiceSelf : A JSON structure which describes the Basemap Styles Service. Includes a list of all supported languages, worldviews, and places.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceSelf {
    /// Name of the service.
    #[serde(rename = "name")]
    pub name: String,
    /// Version of the service that you are using.
    #[serde(rename = "version")]
    pub version: String,
    /// Description of the service.
    #[serde(rename = "description")]
    pub description: String,
    /// Supported languages that can be passed to the {?language} parameters.
    #[serde(rename = "languages")]
    pub languages: Vec<models::ServiceSelfLanguagesInner>,
    /// Supported worldviews that can be passed to the {?worldview} parameters.
    #[serde(rename = "worldviews")]
    pub worldviews: Vec<models::ServiceSelfWorldviewsInner>,
    /// Supported places values that can be passed to the {?places} parameters.
    #[serde(rename = "places")]
    pub places: Vec<models::ServiceSelfPlacesInner>,
    /// URL that points to self.
    #[serde(rename = "selfUrl")]
    pub self_url: String,
    /// URL that points to styles self.
    #[serde(rename = "stylesUrl")]
    pub styles_url: String,
    /// URL that points to webmaps self.
    #[serde(rename = "webmapsUrl")]
    pub webmaps_url: String,
}

impl ServiceSelf {
    /// A JSON structure which describes the Basemap Styles Service. Includes a list of all supported languages, worldviews, and places.
    pub fn new(name: String, version: String, description: String, languages: Vec<models::ServiceSelfLanguagesInner>, worldviews: Vec<models::ServiceSelfWorldviewsInner>, places: Vec<models::ServiceSelfPlacesInner>, self_url: String, styles_url: String, webmaps_url: String) -> ServiceSelf {
        ServiceSelf {
            name,
            version,
            description,
            languages,
            worldviews,
            places,
            self_url,
            styles_url,
            webmaps_url,
        }
    }
}

